// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package todo

type Entity interface {
	IsEntity()
}

type Thing interface {
	IsThing()
}

type Item struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Done *bool  `json:"done"`
}

func (Item) IsThing() {}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

func (Todo) IsThing() {}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
