// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package todo

type Thing interface {
	IsThing()
}

type Item struct {
	ID     string    `json:"id"`
	Name   string    `json:"name"`
	Done   *bool     `json:"done"`
	Fields *[]string `json:"fields"`
}

func (Item) IsThing()   {}
func (Item) Is_Entity() {}

type List struct {
	ID    string  `json:"id"`
	Todos []*Todo `json:"todos"`
}

func (List) Is_Entity() {}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

func (Todo) IsThing()   {}
func (Todo) Is_Entity() {}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
